version: '3'

services:

  nginx:
    container_name: nginx
    build: 
      context: node/nginx
      dockerfile: Dockerfile
    networks:
      - desafio_node_network
    tty: true
    ports:
      - 80:80
    depends_on:
      app_node:
        condition: service_started
      database:
        condition: service_healthy

  app_node:
    container_name: node
    build: 
      context: node
      dockerfile: DockerFile.node
    networks:
      - desafio_node_network
    entrypoint: ["sh", "-c", "npx sequelize-cli db:migrate && node index.js"]
    tty: true
    environment:
      - DB_NAME=sequelizenode
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_HOST=db-mysql
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: db-mysql
    build: 
      context: ./node/mysql
      dockerfile: Dockerfile.mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - desafio_node_network
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=sequelizenode
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 10s

networks:
  desafio_node_network:
    driver: bridge